### ISSUE TITLE
Add to npm

### ISSUE THREAD

**Issue by medoingthings** [appleboy/normalize.scss#8]
Hey Bo-Yi,

would you mind making this very useful fork available to npm? That would come in real handy, since over there is only the version that requires Compass.

I’m dropping Bower for a project, because one system for handling dependencies is better than two in my case.

Thanks for your work!

Cheers,
Mark

**Comment by appleboy** [comment]
@medoingthings 

https://www.npmjs.com/package/node.normalize.scss

```
npm install --save node.normalize.scss
```

**Comment by medoingthings** [comment]
Nice, thanks! Much appreciated.

**Comment by appleboy** [comment]
@medoingthings :+1:
